#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        SERVICE_XPATH_NAME="sensors"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if ! omv_config_exists "${SERVICE_XPATH}"; then
            echo "Initial configuration."
            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_element "${SERVICE_XPATH}" "cpuenable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "sysfanenable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "cpufanenable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "mbtemp" "0"
        fi

        if ! grep -q "LoadPlugin sensors" /etc/collectd/collectd.conf; then
            /usr/sbin/omv-sensors-detect > /dev/null 2>&1
            cat <<EOF >> /etc/collectd/collectd.conf
LoadPlugin sensors

EOF
            /etc/init.d/collectd restart > /dev/null 2>&1
        fi

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0
