#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        SERVICE_XPATH_NAME="sensors"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if ! omv_config_exists "${SERVICE_XPATH}"; then
            echo "Initial configuration."
            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_element "${SERVICE_XPATH}" "cpuenable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "sysfanenable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "cpufanenable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "mbtemp" "0"
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/tabmain"; then
            omv_config_add_element "${SERVICE_XPATH}" "tabmain" "OMV Sensors"
            omv_config_add_element "${SERVICE_XPATH}" "tabcputemp" "CPU Temp"
            omv_config_add_element "${SERVICE_XPATH}" "tabmbtemp" "MotherBoard Temp"
            omv_config_add_element "${SERVICE_XPATH}" "tabcpufan" "CPU fan speed"
            omv_config_add_element "${SERVICE_XPATH}" "tabsysfan" "SYS fan speed"
            omv_config_add_element "${SERVICE_XPATH}" "graphcputitle" "CPU temperature"
            omv_config_add_element "${SERVICE_XPATH}" "graphmbtitle" "MB temperature"
            omv_config_add_element "${SERVICE_XPATH}" "graphcfantitle" "CPU fan speed"
            omv_config_add_element "${SERVICE_XPATH}" "graphsfantitle" "System fan speed"
            omv_config_add_element "${SERVICE_XPATH}" "linecputemp" "CPU"
            omv_config_add_element "${SERVICE_XPATH}" "linecpufan" "CPU Fan"
            omv_config_add_element "${SERVICE_XPATH}" "linembtemp" "MB"
            omv_config_add_element "${SERVICE_XPATH}" "linesysfan" "SYS Fan"
        fi

        if ! grep -q "LoadPlugin sensors" /etc/collectd/collectd.conf; then
            /usr/sbin/omv-sensors-detect --auto
            cat <<EOF >> /etc/collectd/collectd.conf
LoadPlugin sensors

EOF

            service collectd restart > /dev/null 2>&1
        fi

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
